-- Run after 00_setup.sql through 08_runtime_users_settings.sql.
-- Completes the Supabase runtime schema used by the Express API:
-- staff passwords, carts, orders, payments, status history, feedback, and game scores.

begin;

create extension if not exists pgcrypto;

alter table if exists public.users
  add column if not exists password_hash text;

create table if not exists public.orders (
  id bigint generated by default as identity primary key,
  order_key_hash text unique,
  user_id text references public.users(id) on delete set null,
  assigned_deliverer_id text references public.users(id) on delete set null,
  contact_name text not null,
  phone text not null,
  address text,
  order_type text not null check (order_type in ('delivery', 'pickup')),
  delivery_zone_id text references public.delivery_zones(id) on delete set null,
  map_pin_lat double precision,
  map_pin_lng double precision,
  status text not null default 'pending',
  subtotal numeric(12,2) not null default 0 check (subtotal >= 0),
  delivery_cost numeric(12,2) not null default 0 check (delivery_cost >= 0),
  total numeric(12,2) not null default 0 check (total >= 0),
  payment_status text not null default 'unpaid',
  paid_at timestamptz,
  notes text,
  whatsapp_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  product_id uuid references public.products(id) on delete set null,
  name text not null,
  quantity integer not null check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  total_price numeric(12,2) not null default 0 check (total_price >= 0)
);

create table if not exists public.order_status_history (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  from_status text,
  to_status text not null,
  changed_by_user_id text references public.users(id) on delete set null,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.payments (
  id uuid primary key default gen_random_uuid(),
  order_id bigint not null references public.orders(id) on delete cascade,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  method text not null default 'cash',
  status text not null default 'unpaid',
  marked_by_user_id text references public.users(id) on delete set null,
  paid_at timestamptz,
  refunded_at timestamptz,
  note text,
  created_at timestamptz not null default now()
);

create table if not exists public.feedback (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  email text,
  phone text,
  rating integer check (rating is null or rating between 1 and 5),
  message text not null,
  status text not null default 'new',
  created_at timestamptz not null default now()
);

create table if not exists public.app_carts (
  id uuid primary key default gen_random_uuid(),
  session_key text not null unique,
  user_id text references public.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_cart_items (
  id uuid primary key default gen_random_uuid(),
  cart_id uuid not null references public.app_carts(id) on delete cascade,
  product_id uuid not null references public.products(id) on delete restrict,
  quantity integer not null default 1 check (quantity > 0),
  unit_price numeric(12,2) not null default 0 check (unit_price >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (cart_id, product_id)
);

create table if not exists public.last_orders (
  id uuid primary key default gen_random_uuid(),
  session_key text not null unique,
  user_id text references public.users(id) on delete set null,
  items jsonb not null default '[]'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.game_scores (
  id uuid primary key default gen_random_uuid(),
  session_key text unique,
  user_id text unique references public.users(id) on delete set null,
  player_name text check (player_name is null or player_name ~ '^[[:alpha:]]{1,5}$'),
  best_score integer not null default 0 check (best_score >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_orders_phone on public.orders(phone);
create index if not exists idx_orders_status on public.orders(status);
create index if not exists idx_orders_order_type on public.orders(order_type);
create index if not exists idx_orders_created_at on public.orders(created_at desc);
create index if not exists idx_orders_user_id on public.orders(user_id);
create index if not exists idx_orders_assigned_deliverer_id on public.orders(assigned_deliverer_id);
create index if not exists idx_order_items_order_id on public.order_items(order_id);
create index if not exists idx_order_status_history_order_id on public.order_status_history(order_id, created_at);
create index if not exists idx_payments_order_id on public.payments(order_id);
create index if not exists idx_app_cart_items_cart_id on public.app_cart_items(cart_id);
create index if not exists idx_app_cart_items_product_id on public.app_cart_items(product_id);
create index if not exists idx_last_orders_session_key on public.last_orders(session_key);
create index if not exists idx_game_scores_best_score on public.game_scores(best_score desc);
create index if not exists idx_feedback_created_at on public.feedback(created_at desc);

drop trigger if exists trg_orders_updated_at on public.orders;
create trigger trg_orders_updated_at
before update on public.orders
for each row execute function public.set_updated_at();

drop trigger if exists trg_app_carts_updated_at on public.app_carts;
create trigger trg_app_carts_updated_at
before update on public.app_carts
for each row execute function public.set_updated_at();

drop trigger if exists trg_app_cart_items_updated_at on public.app_cart_items;
create trigger trg_app_cart_items_updated_at
before update on public.app_cart_items
for each row execute function public.set_updated_at();

drop trigger if exists trg_last_orders_updated_at on public.last_orders;
create trigger trg_last_orders_updated_at
before update on public.last_orders
for each row execute function public.set_updated_at();

drop trigger if exists trg_game_scores_updated_at on public.game_scores;
create trigger trg_game_scores_updated_at
before update on public.game_scores
for each row execute function public.set_updated_at();

alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_status_history enable row level security;
alter table public.payments enable row level security;
alter table public.feedback enable row level security;
alter table public.app_carts enable row level security;
alter table public.app_cart_items enable row level security;
alter table public.last_orders enable row level security;
alter table public.game_scores enable row level security;

drop policy if exists "Service role manages orders" on public.orders;
create policy "Service role manages orders" on public.orders
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages order items" on public.order_items;
create policy "Service role manages order items" on public.order_items
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages order status history" on public.order_status_history;
create policy "Service role manages order status history" on public.order_status_history
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages payments" on public.payments;
create policy "Service role manages payments" on public.payments
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages feedback" on public.feedback;
create policy "Service role manages feedback" on public.feedback
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages app carts" on public.app_carts;
create policy "Service role manages app carts" on public.app_carts
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages app cart items" on public.app_cart_items;
create policy "Service role manages app cart items" on public.app_cart_items
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages last orders" on public.last_orders;
create policy "Service role manages last orders" on public.last_orders
for all to service_role using (true) with check (true);

drop policy if exists "Service role manages game scores" on public.game_scores;
create policy "Service role manages game scores" on public.game_scores
for all to service_role using (true) with check (true);

create or replace function public.create_checkout_order(
  p_order_key_hash text,
  p_user_id text,
  p_contact_name text,
  p_phone text,
  p_address text,
  p_order_type text,
  p_delivery_zone_id text,
  p_map_pin_lat double precision,
  p_map_pin_lng double precision,
  p_subtotal numeric,
  p_delivery_cost numeric,
  p_total numeric,
  p_notes text,
  p_whatsapp_message text,
  p_items jsonb,
  p_cart_id uuid default null,
  p_last_session_key text default null,
  p_last_items jsonb default '[]'::jsonb
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  v_order_id bigint;
begin
  insert into public.orders (
    order_key_hash,
    user_id,
    contact_name,
    phone,
    address,
    order_type,
    delivery_zone_id,
    map_pin_lat,
    map_pin_lng,
    subtotal,
    delivery_cost,
    total,
    notes,
    whatsapp_message
  )
  values (
    p_order_key_hash,
    p_user_id,
    p_contact_name,
    p_phone,
    p_address,
    p_order_type,
    p_delivery_zone_id,
    p_map_pin_lat,
    p_map_pin_lng,
    p_subtotal,
    p_delivery_cost,
    p_total,
    p_notes,
    p_whatsapp_message
  )
  returning id into v_order_id;

  insert into public.order_items (order_id, product_id, name, quantity, unit_price, total_price)
  select
    v_order_id,
    nullif(item->>'product_id', '')::uuid,
    item->>'name',
    (item->>'quantity')::integer,
    (item->>'unit_price')::numeric,
    (item->>'total_price')::numeric
  from jsonb_array_elements(p_items) as item;

  insert into public.order_status_history (order_id, to_status, note)
  values (v_order_id, 'pending', 'Comandă plasată online');

  insert into public.payments (order_id, amount, method, status)
  values (v_order_id, p_total, 'cash', 'unpaid');

  if p_last_session_key is not null then
    insert into public.last_orders (session_key, user_id, items)
    values (p_last_session_key, p_user_id, p_last_items)
    on conflict (session_key) do update set
      user_id = excluded.user_id,
      items = excluded.items,
      updated_at = now();
  end if;

  if p_cart_id is not null then
    delete from public.app_cart_items where cart_id = p_cart_id;
  end if;

  return v_order_id;
end;
$$;

grant execute on function public.create_checkout_order(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  double precision,
  double precision,
  numeric,
  numeric,
  numeric,
  text,
  text,
  jsonb,
  uuid,
  text,
  jsonb
) to service_role;

commit;
