-- Run after 15_game_voucher_manual_approval.sql.
--
-- This migration:
--   1. clears the current game leaderboard;
--   2. makes every future score belong to an active customer account;
--   3. derives player_name from the first word of public.users.name
--      (for example, "Tarzan Ceva" becomes "Tarzan");
--   4. guarantees that an active game-record voucher rule exists; and
--   5. assigns every new all-time-record voucher directly to the record
--      holder's user account.
--
-- Existing vouchers and redemption history are deliberately preserved.
-- Vouchers generated by the game remain pending until an administrator
-- approves them, as required by 15_game_voucher_manual_approval.sql.

begin;

lock table public.game_scores in access exclusive mode;

-- Start the leaderboard again from zero. Existing voucher rows that referenced
-- these scores are preserved by the vouchers.game_score_id ON DELETE SET NULL
-- foreign key.
delete from public.game_scores;

alter table public.game_scores
  alter column best_score drop default;

alter table public.game_scores
  drop constraint if exists game_scores_best_score_check;

alter table public.game_scores
  add constraint game_scores_best_score_check
  check (best_score > 0);

create or replace function public.customer_first_name(p_full_name text)
returns text
language sql
immutable
parallel safe
as $$
  select nullif(
    split_part(
      regexp_replace(btrim(coalesce(p_full_name, '')), '[[:space:]]+', ' ', 'g'),
      ' ',
      1
    ),
    ''
  );
$$;

alter table public.game_scores
  drop constraint if exists game_scores_player_name_check;

alter table public.game_scores
  add constraint game_scores_player_name_check
  check (
    player_name is not null
    and player_name = btrim(player_name)
    and char_length(player_name) > 0
  );

-- A leaderboard record must belong to an account so its reward can always be
-- shown under Account > Voucherele mele.
alter table public.game_scores
  alter column user_id set not null;

alter table public.game_scores
  alter column session_key drop not null;

alter table public.game_scores
  drop constraint if exists game_scores_user_id_fkey;

alter table public.game_scores
  add constraint game_scores_user_id_fkey
  foreign key (user_id)
  references public.users(id)
  on delete cascade;

create or replace function public.set_game_score_customer_first_name()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer public.users%rowtype;
  v_first_name text;
begin
  select *
  into v_customer
  from public.users
  where id = new.user_id;

  if not found then
    raise exception 'Contul clientului nu există.';
  end if;

  if v_customer.role <> 'customer' then
    raise exception 'Doar conturile de client pot salva recorduri.';
  end if;

  if not v_customer."isActive" then
    raise exception 'Contul clientului nu este activ.';
  end if;

  v_first_name := public.customer_first_name(v_customer.name);
  if v_first_name is null then
    raise exception 'Completează numele clientului înainte de a salva recordul.';
  end if;

  new.player_name := v_first_name;

  -- Scores are account-owned. Keeping a browser session on the row would make
  -- two customers using the same browser conflict with the session_key unique
  -- constraint.
  new.session_key := null;

  return new;
end;
$$;

drop trigger if exists trg_game_scores_customer_first_name on public.game_scores;
create trigger trg_game_scores_customer_first_name
before insert or update of user_id, player_name
on public.game_scores
for each row
execute function public.set_game_score_customer_first_name();

-- Keep an existing score label synchronized if the customer changes their
-- full name later.
create or replace function public.sync_game_score_customer_first_name()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.name is distinct from old.name then
    update public.game_scores
    set player_name = public.customer_first_name(new.name)
    where user_id = new.id;
  end if;

  return new;
end;
$$;

drop trigger if exists trg_users_sync_game_score_customer_first_name on public.users;
create trigger trg_users_sync_game_score_customer_first_name
after update of name
on public.users
for each row
execute function public.sync_game_score_customer_first_name();

-- Reuse the configured record reward when one exists. If no rule has ever been
-- configured, create and activate the same 15% / 14-day default shown in the
-- admin voucher panel.
do $$
declare
  v_rule_id uuid;
begin
  select id
  into v_rule_id
  from public.voucher_rules
  where trigger_type = 'game_record'
  order by is_active desc, updated_at desc
  limit 1;

  if v_rule_id is null then
    insert into public.voucher_rules (
      name,
      trigger_type,
      discount_type,
      discount_value,
      maximum_discount,
      minimum_subtotal,
      validity_days,
      code_prefix,
      requires_approval,
      is_active
    )
    values (
      'Recompensă record joc',
      'game_record',
      'percentage',
      15,
      null,
      0,
      14,
      'RECORD',
      true,
      true
    )
    returning id into v_rule_id;
  else
    update public.voucher_rules
    set is_active = false
    where trigger_type = 'game_record'
      and id <> v_rule_id
      and is_active = true;

    update public.voucher_rules
    set is_active = true,
        requires_approval = true
    where id = v_rule_id;
  end if;
end;
$$;

create or replace function public.issue_game_record_voucher(
  p_rule_id uuid,
  p_game_score_id uuid,
  p_user_id text,
  p_session_key text,
  p_source_score integer,
  p_previous_record_score integer,
  p_created_by_user_id text default null
)
returns public.vouchers
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rule public.voucher_rules%rowtype;
  v_voucher public.vouchers%rowtype;
begin
  if p_user_id is null then
    raise exception 'Voucherul de record trebuie atribuit unui cont de client.';
  end if;

  if not exists (
    select 1
    from public.game_scores
    where id = p_game_score_id
      and user_id = p_user_id
  ) then
    raise exception 'Recordul nu aparține contului clientului.';
  end if;

  select *
  into v_rule
  from public.voucher_rules
  where id = p_rule_id
    and trigger_type = 'game_record'
    and is_active = true;

  if not found then
    raise exception 'Regula de voucher pentru record nu este activă.';
  end if;

  insert into public.vouchers (
    rule_id,
    code,
    name,
    description,
    status,
    source_type,
    user_id,
    session_key,
    game_score_id,
    source_score,
    previous_record_score,
    discount_type,
    discount_value,
    maximum_discount,
    minimum_subtotal,
    valid_from,
    expires_at,
    max_redemptions,
    created_by_user_id,
    approved_by_user_id,
    approved_at
  )
  values (
    v_rule.id,
    public.generate_voucher_code(v_rule.code_prefix),
    v_rule.name,
    'Voucher emis pentru recordul all-time la Aventura Micului.',
    'pending',
    'game_record',
    p_user_id,
    null,
    p_game_score_id,
    p_source_score,
    p_previous_record_score,
    v_rule.discount_type,
    v_rule.discount_value,
    v_rule.maximum_discount,
    v_rule.minimum_subtotal,
    now(),
    case
      when v_rule.validity_days is null then null
      else now() + make_interval(days => v_rule.validity_days)
    end,
    1,
    p_created_by_user_id,
    null,
    null
  )
  on conflict (rule_id, game_score_id, source_score)
    where source_type = 'game_record'
      and rule_id is not null
      and game_score_id is not null
      and source_score is not null
  do nothing
  returning * into v_voucher;

  if v_voucher.id is null then
    select *
    into v_voucher
    from public.vouchers
    where rule_id = v_rule.id
      and game_score_id = p_game_score_id
      and source_score = p_source_score
      and source_type = 'game_record'
    limit 1;
  end if;

  return v_voucher;
end;
$$;

-- Keep the existing RPC signature so the current API can deploy this database
-- migration independently. p_player_name is intentionally ignored.
create or replace function public.save_game_score_with_reward(
  p_session_key text,
  p_user_id text,
  p_score integer,
  p_player_name text
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_customer public.users%rowtype;
  v_previous_record_score integer := 0;
  v_saved public.game_scores%rowtype;
  v_rule_id uuid;
  v_reward public.vouchers%rowtype;
  v_player_name text;
  v_is_new_global_record boolean := false;
begin
  if p_session_key is null or length(btrim(p_session_key)) < 8 then
    raise exception 'Sesiunea jocului nu este validă.';
  end if;

  if p_user_id is null then
    raise exception 'Autentifică-te într-un cont de client pentru a salva scorul.';
  end if;

  if p_score is null or p_score <= 0 then
    raise exception 'Scorul trebuie să fie mai mare decât 0.';
  end if;

  select *
  into v_customer
  from public.users
  where id = p_user_id
    and role = 'customer'
    and "isActive" = true;

  if not found then
    raise exception 'Contul clientului nu există sau nu este activ.';
  end if;

  v_player_name := public.customer_first_name(v_customer.name);
  if v_player_name is null then
    raise exception 'Completează numele clientului înainte de a salva scorul.';
  end if;

  -- Serialize global-record checks and reward creation so two simultaneous
  -- saves cannot both win the same all-time-record event.
  perform pg_advisory_xact_lock(
    hashtext('public.game_scores.global_record_reward')
  );

  select coalesce(max(best_score), 0)
  into v_previous_record_score
  from public.game_scores;

  insert into public.game_scores (
    session_key,
    user_id,
    player_name,
    best_score
  )
  values (
    null,
    p_user_id,
    v_player_name,
    p_score
  )
  on conflict (user_id)
  do update
  set session_key = null,
      player_name = excluded.player_name,
      best_score = greatest(game_scores.best_score, excluded.best_score)
  returning * into v_saved;

  v_is_new_global_record := p_score > v_previous_record_score;

  if v_is_new_global_record then
    select id
    into v_rule_id
    from public.voucher_rules
    where trigger_type = 'game_record'
      and is_active = true
    order by updated_at desc
    limit 1;

    if v_rule_id is null then
      raise exception 'Nu există o regulă activă pentru voucherul de record.';
    end if;

    v_reward := public.issue_game_record_voucher(
      v_rule_id,
      v_saved.id,
      p_user_id,
      null,
      p_score,
      v_previous_record_score,
      null
    );
  end if;

  return jsonb_build_object(
    'id', v_saved.id,
    'bestScore', v_saved.best_score,
    'playerName', v_saved.player_name,
    'isNewGlobalRecord', v_is_new_global_record,
    'reward', case
      when v_reward.id is null then null
      else jsonb_build_object(
        'id', v_reward.id,
        'status', v_reward.status,
        'code', case when v_reward.status = 'active' then v_reward.code else null end,
        'discountType', v_reward.discount_type,
        'discountValue', v_reward.discount_value,
        'maximumDiscount', v_reward.maximum_discount,
        'minimumSubtotal', v_reward.minimum_subtotal,
        'expiresAt', v_reward.expires_at,
        'message', case
          when v_reward.status = 'active'
            then 'Felicitări! Ai primit un voucher pentru noul record.'
          else 'Felicitări! Voucherul pentru record așteaptă aprobarea administratorului.'
        end
      )
    end
  );
end;
$$;

create or replace function public.issue_current_game_record_voucher(
  p_admin_user_id text
)
returns public.vouchers
language plpgsql
security definer
set search_path = public
as $$
declare
  v_rule_id uuid;
  v_score public.game_scores%rowtype;
  v_reward public.vouchers%rowtype;
begin
  perform pg_advisory_xact_lock(
    hashtext('public.game_scores.global_record_reward')
  );

  select id
  into v_rule_id
  from public.voucher_rules
  where trigger_type = 'game_record'
    and is_active = true
  order by updated_at desc
  limit 1;

  if v_rule_id is null then
    raise exception 'Nu există o regulă activă pentru voucherul de record.';
  end if;

  select *
  into v_score
  from public.game_scores
  where user_id is not null
  order by best_score desc, updated_at asc
  limit 1;

  if v_score.id is null or v_score.best_score <= 0 then
    raise exception 'Nu există încă un record eligibil.';
  end if;

  v_reward := public.issue_game_record_voucher(
    v_rule_id,
    v_score.id,
    v_score.user_id,
    null,
    v_score.best_score,
    null,
    p_admin_user_id
  );

  return v_reward;
end;
$$;

grant execute on function public.customer_first_name(text) to service_role;
grant execute on function public.issue_game_record_voucher(
  uuid,
  uuid,
  text,
  text,
  integer,
  integer,
  text
) to service_role;
grant execute on function public.save_game_score_with_reward(
  text,
  text,
  integer,
  text
) to service_role;
grant execute on function public.issue_current_game_record_voucher(text)
to service_role;

commit;
